# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: update-wiki

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v2
#      with:
#        python-version: "3.7"
#    - run: pip3 install pyyaml pandas openpyxl 
    - name: check and htmlize
      run: |
        ./bin/megalodonw.pl 10 ./mglib/Part1.mg ./mglib/Part1.mg
        ./bin/megalodonw.pl 10 ./mglib/t3_xregular.mg ./mglib/t3_xregular.mg
        ./bin/megalodonw.pl 10 ./mglib/oeis-A110451.mg ./mglib/oeis-A110451.mg
        ls mglib/conj/oeis | parallel --will-cite './bin/megalodonw.pl 10 mglib/conj/oeis/{} mglib/conj/oeis/{}'
        for i in `ls mglib/conj/oeis/* | head -n 1000`; do ./bin/megalodonw.pl 10 $i $i; done
        ./bin/megalodonw.pl 20 ./mglib/Part1.mg -pfg -html ./docs/Part1.html ./mglib/Part1.mg > ./pfg/Part1.pfg
        ./bin/megalodonw.pl 20 ./mglib/t3_xregular.mg -pfg -html ./docs/t3_xregular.html ./mglib/t3_xregular.mg > ./pfg/t3_xregular.pfg
        ./bin/megalodonw.pl 20 ./mglib/oeis-A110451.mg -pfg -html ./docs/oeis-A110451.html ./mglib/oeis-A110451.mg > ./pfg/oeis-A110451.pfg
        ls mglib/conj/oeis | parallel --will-cite './bin/megalodonw.pl 20 mglib/conj/oeis/{} -pfg -html docs/conj/oeis/{}.html mglib/conj/oeis/{} > pfg/conj/oeis/{}.pfg'
        find docs/ -type f | perl -pe 'BEGIN {print "<html><body>\n";} s/^docs.(.*)$/<a href="$1">$1<\/a>/; END {print "</body></html>\n"}' > ./docs/index.html
    - name: update the repo
      run: |
        git config --local user.name "wiki updater"
        git config --local user.email "mgwiki@github.com"
        git add .
        git commit -m "Update mgwiki" || true
    - name: push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
