# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: update-wiki

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v2
#      with:
#        python-version: "3.7"
#    - run: pip3 install pyyaml pandas openpyxl 
    - name: check and htmlize
      run: |
        find mglib/ -type f | parallel --will-cite './bin/megalodonw.pl 20 {} {}'
        ls sig | parallel --will-cite './bin/megalodonw.pl 10 sig/{} sig/{}'
        ls sig | parallel --will-cite './bin/megalodonw.pl 40 sig/{} -pfg -html docs/sig/{}.html sig/{} > pfg/sig/{}.pfg'
        find mglib/ -type f | perl -pe 's/^mglib\///' | parallel --will-cite './bin/megalodonw.pl 20 mglib/{} -pfg -html docs/{}.html mglib/{} > pfg/{}.pfg'
        find docs/ -type f | perl -pe 'BEGIN {print "<html><body>\n";} s/^docs.(.*)$/<a href="$1">$1<\/a>/; END {print "</body></html>\n"}' > ./docs/index.html
        for i in `find docs/ -type f`; do perl -e '$h=$ARGV[0]; while(<>) {if(m/<a name=([^\/]+)/) {$l=$1} while(m/php\?b=([0-9A-Fa-f]{64})\b/g) { print "$1:\047$h\047:$l\n"}   }' $i; done > etc/rindex.txt
    - name: update the repo
      run: |
        git config --local user.name "wiki updater"
        git config --local user.email "mgwiki@github.com"
        git add .
        git commit -m "Update mgwiki" || true
    - name: push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
